from ntru import Ntru

#Kaustubh
print("Public Key is generated by using Parameters: ", end = '')
print("N = 7, p = 29, and q = 491531")
Kaustubh = Ntru(7, 29, 491531)
# f(x) = 1 + x - x^2 - x^4 + x^5
f = [1, 1, -1, 0, -1, 1]
# g(x) = -1 + x^2 + x^3 - x^6
g = [-1, 0, 1, 1, 0, 0, -1]
d = 2
print("f(x)= ", f)
print("g(x)= ", g)
print("d   = ", d, "\n\n")
Kaustubh.genPublicKey(f, g, 2)
pub_key = Kaustubh.getPublicKey()
print("Public Key Generated by Kaustubh: ", pub_key, "\n\n")

#Divyansh
Divyansh = Ntru(7, 29, 491531)
Divyansh.setPublicKey(pub_key)
message = [1, 0, 1, 0, 1, 1, 1]
print("Original Message to be send: ", message)

# r(x) = -1 - x + x^2 + x^3
ranPol = [-1, -1, 1, 1]
print("Random Polynomial: ", ranPol)
encryptedMessage = Kaustubh.encrypt(message, ranPol)
print("Encrypted Message to be send: ", encryptedMessage, "\n\n")

#BOB
print("Kaustubh decrypts message sent to him by Divyansh")
print("Decrypted Message: ", Kaustubh.decrypt(encryptedMessage))
